development:
  adapter: postgresql
  encoding: unicode
  database: app2_development
  pool: 10
  username: app2
  password: app2

test:
  adapter: postgresql
  encoding: unicode
  database: app2_test
  pool: 5
  username: app2
  password: app2

production:
  adapter: postgresql
  encoding: unicode
  database: app2_production
  pool: 5
  username: app2
  password:
